-- DROP TABLE IF EXISTS;
CREATE TABLE Comuna (
  ID_COMUNA SERIAL NOT NULL,
  Nombre VARCHAR(255),
  PRIMARY KEY(ID_COMUNA)
);

CREATE TABLE Edificio_Estacionamiento (
  ID_ESTACIONAMIENTO SERIAL NOT NULL,
  ID_COMUNA SERIAL NOT NULL,
  Nombre VARCHAR(255),
  PRIMARY KEY(ID_ESTACIONAMIENTO),
  FOREIGN KEY (ID_COMUNA) REFERENCES Comuna(ID_COMUNA)
);

CREATE TABLE Lugar (
  ID_LUGAR SERIAL NOT NULL,
  ID_ESTACIONAMIENTO SERIAL NOT NULL,
  numero_lugar VARCHAR(64) NOT NULL,
  PRIMARY KEY(ID_LUGAR),
  FOREIGN KEY (ID_ESTACIONAMIENTO) REFERENCES Edificio_Estacionamiento(ID_ESTACIONAMIENTO)
);

CREATE TABLE Modelo (
  ID_MODELO SERIAL NOT NULL,
  Nombre_modelo VARCHAR(255),
  Descripcion_modelo TEXT,
  Marca VARCHAR(100),
  PRIMARY KEY(ID_MODELO)
);
CREATE TABLE Sueldo (
  ID_SUELDO SERIAL NOT NULL,
  Valor_Bruto INT,
  Valor_Liquido INT,
  PRIMARY KEY(ID_SUELDO)
);

CREATE TABLE Vehiculo (
  ID_VEHICULO SERIAL NOT NULL,
  ID_MODELO SERIAL NOT NULL,
  Patente VARCHAR(20),
  Color VARCHAR(50),
  Estado VARCHAR(50),
  PRIMARY KEY(ID_VEHICULO),
  FOREIGN KEY (ID_MODELO) REFERENCES Modelo(ID_MODELO)
);



CREATE TABLE Empleado (
  ID_EMPLEADO SERIAL NOT NULL,
  ID_ESTACIONAMIENTO SERIAL NOT NULL,
  ID_SUELDO SERIAL NOT NULL,
  Nombre VARCHAR(100),
  Edad INT,
  N_Contacto VARCHAR(20),
  PRIMARY KEY(ID_EMPLEADO),
  FOREIGN KEY (ID_ESTACIONAMIENTO) REFERENCES Edificio_Estacionamiento(ID_ESTACIONAMIENTO),
  FOREIGN KEY (ID_SUELDO) REFERENCES Sueldo(ID_SUELDO)
);


CREATE TABLE Cliente (
  ID_CLIENTE SERIAL NOT NULL,
  Nombre VARCHAR(255),
  ID_COMUNA SERIAL NOT NULL,
  PRIMARY KEY(ID_CLIENTE),
  FOREIGN KEY (ID_COMUNA) REFERENCES Comuna(ID_COMUNA)
);

CREATE TABLE Cliente_Vehiculo (
  ID_CLIENTE_VEHICULO SERIAL NOT NULL,
  ID_CLIENTE SERIAL NOT NULL,
  ID_VEHICULO SERIAL NOT NULL,
  PRIMARY KEY(ID_CLIENTE_VEHICULO),
  FOREIGN KEY (ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE),
  FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculo(ID_VEHICULO)
);

CREATE TABLE Lugar_Cliveh (
  ID_LUGAR_CLIVEH SERIAL NOT NULL,
  ID_CLIENTE_VEHICULO SERIAL NOT NULL,
  ID_LUGAR SERIAL NOT NULL,
  PRIMARY KEY(ID_LUGAR_CLIVEH),
  FOREIGN KEY (ID_CLIENTE_VEHICULO) REFERENCES Cliente_Vehiculo(ID_CLIENTE_VEHICULO),
  FOREIGN KEY (ID_LUGAR) REFERENCES Lugar(ID_LUGAR)
);


CREATE TABLE Contrato (
  ID_CONTRATO SERIAL NOT NULL,
  ID_ESTACIONAMIENTO SERIAL NOT NULL,
  Detalle TEXT,
  Fecha DATE DEFAULT CURRENT_DATE,
  PRIMARY KEY(ID_CONTRATO),
  FOREIGN KEY (ID_ESTACIONAMIENTO) REFERENCES Edificio_Estacionamiento(ID_ESTACIONAMIENTO)
);

CREATE TABLE Pago (
  ID_PAGO SERIAL NOT NULL,
  ID_CONTRATO SERIAL NOT NULL,
  Valor INT,
  Fecha_pago DATE DEFAULT CURRENT_DATE,
  PRIMARY KEY(ID_PAGO),
  FOREIGN KEY (ID_CONTRATO) REFERENCES Contrato(ID_CONTRATO)
);



